version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
      prod-dependencies:
        patterns:
          - "*"
        dependency-type: "production"
    ignore:
      - dependency-name: "alpinejs"
      - dependency-name: "tailwindcss"
      - dependency-name: "rollup"
      - dependency-name: "edge.js"
